export const SCREENS = {
    TABS: "Tabs",
    HOME: "Home",
    PROFILE: "Profile",
    LOGIN: "Login",
    SIGNUP: "Signup",
    RESULT: "Result",
    DISEASE_LIST: "DiseaseList",
};

export const IMAGES = {
    Apple___Apple_scab: require("../../assets/images/Apple/Apple___Apple_scab.jpeg"),
    Apple___Black_rot: require("../../assets/images/Apple/Apple___Black_rot.jpeg"),
    Apple___Cedar_apple_rust: require("../../assets/images/Apple/Apple___Cedar_apple_rust.jpeg"),
    "Cherry_(including_sour)___Powdery_mildew": require("../../assets/images/Cherry/Cherry_(including_sour)___Powdery_mildew.jpeg"),
    "Cherry_(including_sour)___healthy": require("../../assets/images/Cherry/Cherry_(including_sour)___healthy.jpeg"),
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": require("../../assets/images/Corn/Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot.jpeg"),
    "Corn_(maize)___Common_rust_": require("../../assets/images/Corn/Corn_(maize)___Common_rust.jpeg"),
    "Corn_(maize)___Northern_Leaf_Blight": require("../../assets/images/Corn/Corn_(maize)___Northern_Leaf_Blight.jpeg"),
    Grape___Black_rot: require("../../assets/images/Grapes/Grape___Black_rot.jpeg"),
    "Grape___Esca_(Black_Measles)": require("../../assets/images/Grapes/Grape___Esca_(Black_Measles).jpeg"),
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": require("../../assets/images/Grapes/Grape___Leaf_blight_(Isariopsis_Leaf_Spot).jpeg"),
    Potato___Early_blight: require("../../assets/images/Potato/Potato___Early_blight.jpeg"),
    Potato___Late_blight: require("../../assets/images/Potato/Potato___Late_blight.jpeg"),
    Tomato___Bacterial_spot: require("../../assets/images/Tomato/Tomato___Bacterial_spot.jpeg"),
    Tomato___Early_blight: require("../../assets/images/Tomato/Tomato___Early_blight.jpeg"),
    Tomato___Late_blight: require("../../assets/images/Tomato/Tomato___Late_blight.jpeg"),
    Tomato___Leaf_Mold: require("../../assets/images/Tomato/Tomato___Leaf_Mold.jpeg"),
    Tomato___Septoria_leaf_spot: require("../../assets/images/Tomato/Tomato___Septoria_leaf_spot.jpeg"),
    "Tomato___Spider_mites%20Two-spotted_spider_mite": require("../../assets/images/Tomato/Tomato___Spider_mites Two-spotted_spider_mite.jpeg"),
    Tomato___Target_Spot: require("../../assets/images/Tomato/Tomato___Target_Spot.jpeg"),
    Tomato___Tomato_Yellow_Leaf_Curl_Virus: require("../../assets/images/Tomato/Tomato___Tomato_Yellow_Leaf_Curl_Virus.jpeg"),
    Tomato___Tomato_mosaic_virus: require("../../assets/images/Tomato/Tomato___Tomato_mosaic_virus.jpeg"),
    default: require("../../assets/images/test1.jpg"),
};
